name: quality

on:
  push:

jobs:
  style:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "26"
          elixir-version: "1.15.6"
      - uses: actions/cache@v3
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}

      - run: mix deps.get
      - run: mix format --check-formatted

  test:
    runs-on: ubuntu-latest
    services:
      database:
        image: mysql:8.1.0-oracle
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: please
          DEV_DATABASE_URL: mysql://root:please@localhost/arvore_dev
    steps:
      - uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "26"
          elixir-version: "1.15.6"
      - uses: actions/cache@v3
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}

      - run: mix deps.get
      - run: mix compile
      - run: mix test
